version: '3.8'
services:
  question-service:
    build:
      context: ./question-service
    ports:
      - "8080:8080"

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
      
  matching-service:
    build:
      context: ./matching-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

