version: '3.8'
services:
  question-service:
    build:
      context: ./question-service
    ports:
      - "8080:8080"
    environment:
      - MONGODB_ENDPOINT=peerprep.xvavl.mongodb.net
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=g26password

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    environment:
      - MONGODB_ENDPOINT=peerprep.xvavl.mongodb.net
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=g26password
