version: '3.8'
services:
  question-service:
    build:
      context: ./question-service
    ports:
      - "8080:8080"

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
